### ISSUE TITLE
todo: download high resolution basal topography data

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/LEAP-Cryo-planning#13]
Download high resolution basal topography data, starting with the Thwaites Glacier (TG) data from [This paper](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021GL096564).
This paper was lead by @hoffmaao's. 
The data can be accessed here: https://digital.lib.washington.edu/researchworks/handle/1773/48648

In our meeting this morning, @hoffmaao said that other similar data exist in Greenland. Downloading that data can be the next step after getting the TG data.  

cc @Templar129

**Comment by Templar129** [comment]
Day 1:

- Downloaded the topography data
- Tried to plot the 2-D topology graph on Python using Matplotlib, the result graph was not in correct shape, and the color map looks not good.
- Install pygmt venv and tried to use pygmt to do the ploting

**Comment by jkingslake** [comment]
if you have the data downloaded, feel free to close this issue (you get a good feeling of progress when you close issues!).

Then start another one about plotting.

**Comment by Templar129** [comment]
Yeah, this makes sense, Since the data has been downloaded and plotted, this comment should be closed.
