### ISSUE TITLE
Question about installing Firedrake

### ISSUE THREAD

**Issue by Templar129** [ldeo-glaciology/LEAP-Cryo-planning#5]
Hi, 
I just tried to install firedrake based on the instruction from their [website.](https://firedrakeproject.org/download.html) 
I used 
python3 firedrake-install
to install it on my mac with apple silicon.
For installing some dependent packages, such gcc, make, etc. , it would pop out bugs because of the apple silicon. What I did was simply and manually install them through homebrew in my terminal.
After that it all went well until building PETSc.
I encountered a problem that stopped the installation, it says in the log that, 
Unknown Fortran name mangling: Are you sure the C and Fortran compilers are compatible?
  Perhaps one is 64 bit and one is 32 bit?
I have checked my gcc and gfortran, both are updated version. 
I am not sure how to solve this problem, so I would really appreciate any advise or help.

I have attached the log for the installation, please refer to the last section about the problem I mentioned.
Best,
Hengbo
[firedrake-install.log](https://github.com/ldeo-glaciology/LEAP-Cryo-planning/files/10876466/firedrake-install.log)

**Comment by Templar129** [comment]
I was trying to find if others have face same issue, it turned out this problems/bug is specific to apple silicon, and I did not find too much useful information to help me solve it. 
I will try if I can install it on a Linux environment. 
If anyone has ideas about how I can further install and debug it on M1 mac, please let me know, I really appreciate any help.

Best,
Hengbo

**Comment by jkingslake** [comment]
sorry I missed this one too!

**Comment by jkingslake** [comment]
I do not have an M1 mac, so I havent been trouble shooting this. 

I suggest going through the steps I laid out in #8 and then if the you still have the same problem, start a new discussion on the firedrake github. They were very responsive when I asked a question on there: https://github.com/firedrakeproject/firedrake/discussions/2851#discussioncomment-5508076

If you are instead going to stick to linux and do not need a mac installation, I will close this issue.
