### ISSUE TITLE
Icepack installation

### ISSUE THREAD

**Issue by Templar129** [ldeo-glaciology/LEAP-Cryo-planning#6]
Hi,
I have successfully installed icepack under a Linux environment, but with a problem not sure about.
During the installation, I continuously encountered a problem about downloading NETCDF during building PETSC. I searched online and find some people similarly using icepack package choose to install PETSC with this command : '--minimal-petsc'. So I tried this too, and it works, the installation was fast and successful, but I am not sure if there is any drawbacks of doing so, if anyone knows, please let me know.

**Comment by jkingslake** [comment]
Hi @Templar129, sorry I missed this. Next time feel free to mention my name in the issue, or assign me to the issue, so that I see the issue and will respond faster.

**Comment by jkingslake** [comment]
Great work on getting this installed. 

When exactly did you  use that option? Perhaps you  can include a detailed description of the steps you took here.

**Comment by jkingslake** [comment]
and to answer your question, no I do not know a way around this, or if it will be an issue. Maybe just move forward with using the installation you have and bear in mind that when you have any issues later on with missing packages, or functionality, it could be due to this.
