### ISSUE TITLE
issue installing h5py during firdrake install

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/LEAP-Cryo-planning#7]
@Templar129, I tried
`python3 firedrake-install --minimal-petsc`

and it failed at the stage of installing h5py

Did you have the same issue? What did you do to get round it if so? 
I tried installing it separately with homebrew (`brew install h5py`) but it didn't find the package.  I tried pip installing it, which worked, but I still ran into the same issue when trying to install firedrake afterwards.  

Any ideas?

cc @hoffmaao

**Comment by Templar129** [comment]
Hi professor @jkingslake,
If you are under Linux environment, maybe try using apt to install the package h5py. Here is the one I used:
```

sudo apt update
sudo apt install python-h5py

``` 
For package I did not have in my Linux, I used this apt which is quite similar to home brew.
Also, each time the installation run into an error, there should be a error log. Could you attach the error log, maybe there is an explanation for this error in it.

**Comment by jkingslake** [comment]
Simple question, @Templar129: I have successfully installed firedrake on an ubuntu machine, not what do I do to install icepack?

**Comment by Templar129** [comment]
@jkingslake Hi,
My way of doing this is that:
`firedrake-update --install <package name>`
In our case, it is simply 
`firedrake-update --install icepack`
Then it should work.
To see how this code works, you can refer to this:
`firedrake-update --help`,
it would give all the sub options and functions.
I hope this could help, and let me know if it does not work.

**Comment by jkingslake** [comment]
Thanks. 

I found that I needed to first activate the firedrake environment
`source firedrake/bin/activate`
then run
`python3 firedrake/bin/firedrake-update --install icepack`
then it seemed to complete the update successfully.

**Comment by Templar129** [comment]
Oh yes, sorry I forget to mention. This is a required step.

**Comment by jkingslake** [comment]
OK, I finally got it working! 

After the firedrake-install step I followed instructions here: https://icepack.github.io/install/
except that I additionally had to use
`sudo apt install jupyter-notebook` 
before opening the tutorial notebooks.

(note this is on Ubuntu 22.04.1LYS, installed on an iMac13,2). 

Thanks for your help!
